# Generated by Django 5.0.3 on 2024-03-20 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(default=0, verbose_name='Ідентифікатор чату')),
                ('title', models.CharField(max_length=300, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'чат',
                'verbose_name_plural': 'чати',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=600, verbose_name='Текст повідомлення')),
                ('description', models.TextField(verbose_name='Опис')),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PromotionMaker.chat', verbose_name='Чат')),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'пости',
            },
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(verbose_name='Порядок відображення')),
                ('title', models.CharField(max_length=200, verbose_name='Текст відображення кнопки')),
                ('url', models.CharField(max_length=600, verbose_name='Посилання в кнопці')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PromotionMaker.post')),
            ],
            options={
                'verbose_name': 'кнопка',
                'verbose_name_plural': 'кнопки',
            },
        ),
    ]
