# Generated by Django 5.0.3 on 2024-05-05 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PromotionMaker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscribe_links', to='PromotionMaker.chat', verbose_name='Базовий чат')),
                ('subscribe_chat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscribed_links', to='PromotionMaker.chat', verbose_name='Спільнота-підписка')),
            ],
        ),
    ]
