# Generated by Django 5.0.3 on 2024-05-05 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PromotionMaker', '0002_subscribelink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribelink',
            options={'verbose_name': 'Підписку', 'verbose_name_plural': 'Підписки'},
        ),
        migrations.AddField(
            model_name='subscribelink',
            name='subscribe_link',
            field=models.CharField(default=' ', max_length=200, verbose_name='Посилання для підписки'),
        ),
        migrations.AlterField(
            model_name='subscribelink',
            name='subscribe_chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscribed_links', to='PromotionMaker.chat', verbose_name='Спільнота для підписки'),
        ),
    ]
