# Generated by Django 5.0.3 on 2024-06-20 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PromotionMaker', '0003_alter_subscribelink_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date_promotion', models.DateField(null=True, verbose_name='Дата завершення постингу')),
                ('message_id', models.IntegerField(verbose_name='ID повідомлення поста реклами')),
                ('chat_message_id', models.IntegerField(verbose_name='ID чату реклами')),
                ('chat_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='promotion_posts', to='PromotionMaker.chat', verbose_name='Чат для реклами')),
            ],
            options={
                'verbose_name': 'Рекламний пост',
                'verbose_name_plural': 'Рекламні пости',
            },
        ),
    ]
