# Generated by Django 5.1.6 on 2025-02-07 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PromotionMaker', '0005_spamfiltermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteToChatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500, verbose_name='Нікнейм юзера')),
                ('is_invited', models.BooleanField(blank=True, default=False, null=True)),
                ('chat_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='invite_to_chat', to='PromotionMaker.chat', verbose_name='Чат інвайту')),
            ],
            options={
                'verbose_name': 'Інвайт в чат',
                'verbose_name_plural': 'Інвайти в чат',
            },
        ),
    ]
